name: Regenerate
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Delete all
        run: |
          shopt -s extglob
          rm -rf !(README.md|.git|repos.txt)
          shopt -u extglob
      - name: Generate
        run: nix run github:silvarc141/reapkgs -- -gprq -i ./repos.txt -o .
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --quiet HEAD || (git commit -am "flake regeneration $(date +'%Y-%m-%d')" && git push)
